import {supabaseFetch} from "@/lib/supabase";import {getSession} from "@/lib/auth";
export type LeadRow={id:string;name:string;business_name?:string;category?:string;city?:string;state?:string;address?:string;phone?:string;website?:string;rating?:number;reviews_count?:number;status:string;notes?:string;source?:string;has_whatsapp?:string;has_website?:boolean;has_phone?:boolean;latitude?:number;longitude?:number;maps_url?:string;created_at:string;updated_at?:string};
const uid=()=>getSession()?.user?.id;const enc=(v:string)=>encodeURIComponent(v);
export async function listMyLeads(limit=500){const id=uid();if(!id)return [];return supabaseFetch<LeadRow[]>("leads?user_id=eq."+id+"&order=created_at.desc&limit="+limit)}
export async function getLead(id:string){const me=uid();if(!me)throw new Error("Faça login.");const rows=await supabaseFetch<LeadRow[]>("leads?id=eq."+enc(id)+"&user_id=eq."+me+"&limit=1");return rows[0]||null}
export async function updateLead(id:string,patch:Partial<LeadRow>){return supabaseFetch<LeadRow[]>("leads?id=eq."+enc(id),{method:"PATCH",headers:{"Prefer":"return=representation"},body:JSON.stringify(patch)})}
export async function deleteLead(id:string){return supabaseFetch("leads?id=eq."+enc(id),{method:"DELETE"})}
export async function createActivity(leadId:string,type:string,title:string,description="",metadata:any={}){const id=uid();if(!id)throw new Error("Faça login.");return supabaseFetch("lead_activities",{method:"POST",headers:{"Prefer":"return=representation"},body:JSON.stringify({lead_id:leadId,user_id:id,type,title,description,metadata})})}
export async function listActivities(leadId:string){const id=uid();if(!id)return [];return supabaseFetch<any[]>("lead_activities?lead_id=eq."+enc(leadId)+"&user_id=eq."+id+"&order=created_at.desc&limit=100")}
export async function createList(name:string,description=""){const id=uid();if(!id)throw new Error("Faça login.");const r=await supabaseFetch<any[]>("lists",{method:"POST",headers:{"Prefer":"return=representation"},body:JSON.stringify({user_id:id,name,description})});return r[0]}
export async function listLists(){const id=uid();if(!id)return [];return supabaseFetch<any[]>("lists?user_id=eq."+id+"&order=created_at.desc")}
export async function addLeadToList(listId:string,leadId:string){return supabaseFetch("list_leads",{method:"POST",headers:{"Prefer":"resolution=ignore-duplicates"},body:JSON.stringify({list_id:listId,lead_id:leadId})})}
export async function removeLeadFromList(listId:string,leadId:string){return supabaseFetch("list_leads?list_id=eq."+enc(listId)+"&lead_id=eq."+enc(leadId),{method:"DELETE"})}
export async function listListLeads(listId:string){return supabaseFetch<LeadRow[]>("leads?select=*,list_leads!inner(list_id)&list_leads.list_id=eq."+enc(listId)+"&order=created_at.desc")}
export async function deleteList(id:string){return supabaseFetch("lists?id=eq."+enc(id),{method:"DELETE"})}
export async function createCampaign(name:string,description=""){const id=uid();if(!id)throw new Error("Faça login.");const r=await supabaseFetch<any[]>("campaigns",{method:"POST",headers:{"Prefer":"return=representation"},body:JSON.stringify({user_id:id,name,description,status:"draft"})});return r[0]}
export async function listCampaigns(){const id=uid();if(!id)return [];return supabaseFetch<any[]>("campaigns?user_id=eq."+id+"&order=created_at.desc")}
export async function saveLead(lead:any){const id=uid();if(!id)throw new Error("Faça login.");const row={user_id:id,google_place_id:lead.google_place_id||null,name:lead.name||"Sem nome",business_name:lead.business_name||lead.name||null,category:lead.category||null,categories:lead.categories||[],phone:lead.phone||null,international_phone:lead.international_phone||null,website:lead.website||null,address:lead.address||null,street:lead.street||null,number:lead.number||null,neighborhood:lead.neighborhood||null,city:lead.city||lead.location||null,state:lead.state||null,postal_code:lead.postal_code||null,country:lead.country||"Brasil",latitude:lead.latitude??null,longitude:lead.longitude??null,rating:lead.rating??null,reviews_count:lead.reviews_count??null,business_status:lead.business_status||null,opening_hours:lead.opening_hours||null,maps_url:lead.maps_url||null,photos:lead.photos||[],types:lead.types||[],has_website:Boolean(lead.website),has_phone:Boolean(lead.phone),has_whatsapp:lead.has_whatsapp||"unknown",status:"new",source:lead.source||"web_search"};if(lead.google_place_id){const old=await supabaseFetch<any[]>("leads?user_id=eq."+id+"&google_place_id=eq."+enc(lead.google_place_id)+"&limit=1");if(old[0])return old[0]}const r=await supabaseFetch<any[]>("leads",{method:"POST",headers:{"Prefer":"return=representation"},body:JSON.stringify(row)});const saved=r[0];if(saved)await createActivity(saved.id,"lead_saved","Lead salvo no HunterX","Lead adicionado à base comercial.",{source:row.source});return saved}
export async function dashboardStats(){const leads=await listMyLeads();const n=(s:string)=>leads.filter(x=>x.status===s).length;return {total:leads.length,new:n("new"),contacted:n("contacted"),interested:n("interested"),negotiation:n("negotiation"),customer:n("customer"),lost:n("lost"),conversion:leads.length?Math.round(n("customer")/leads.length*100):0,recent:leads.slice(0,6)}}
export async function listSearchHistory(){const id=uid();if(!id)return [];return supabaseFetch<any[]>("searches?user_id=eq."+id+"&order=created_at.desc&limit=30")}
export async function listSavedFilters(){const id=uid();if(!id)return [];return supabaseFetch<any[]>("saved_filters?user_id=eq."+id+"&order=created_at.desc")}
export async function saveFilter(name:string,query:string,location:string,filters:any){const id=uid();if(!id)throw new Error("Faça login.");const r=await supabaseFetch<any[]>("saved_filters",{method:"POST",headers:{"Prefer":"return=representation"},body:JSON.stringify({user_id:id,name,query,location,filters})});return r[0]}
export async function deleteFilter(id:string){return supabaseFetch("saved_filters?id=eq."+enc(id),{method:"DELETE"})}
export async function unreadNotifications(){const id=uid();if(!id)return [];return supabaseFetch<any[]>("notifications?user_id=eq."+id+"&read_at=is.null&order=created_at.desc&limit=20")}
export async function markNotificationRead(id:string){return supabaseFetch("notifications?id=eq."+enc(id),{method:"PATCH",body:JSON.stringify({read_at:new Date().toISOString()})})}
export async function getCreditBalance(){const id=uid();if(!id)return 0;const r=await supabaseFetch<any[]>("credit_balances?user_id=eq."+id+"&limit=1");return r[0]?.balance??0}