import {Link,useLocation} from "@tanstack/react-router";
import {useEffect,useState} from "react";
import {AppShell} from "@/components/app/AppShell";
import {PageHeader} from "@/components/app/PageHeader";
import {listMyLeads,updateLead,listLists,createList,listCampaigns,createCampaign,type LeadRow} from "@/services/appData";
import {Search,Plus,Download,BarChart3,MapPin,Brain,Target,Users} from "lucide-react";
export function WorkspacePage({kind}:{kind:string}){
 const [leads,setLeads]=useState<LeadRow[]>([]); const [items,setItems]=useState<any[]>([]); const [name,setName]=useState("");
 useEffect(()=>{if(kind==="leads"||kind==="crm"||kind==="analytics"||kind==="exports")listMyLeads().then(setLeads); if(kind==="lists")listLists().then(setItems); if(kind==="campaigns")listCampaigns().then(setItems)},[kind]);
 const cfg:any={leads:["Meus leads","Sua base comercial salva e pronta para trabalhar.","Base comercial"],crm:["CRM","Acompanhe cada oportunidade no funil.","Pipeline"],lists:["Listas","Organize leads em segmentos reutilizáveis.","Organização"],campaigns:["Campanhas","Planeje suas ações comerciais.","Prospecção"],analytics:["Analytics","Veja a evolução do seu funil.","Inteligência"],exports:["Exportações","Baixe sua base comercial em CSV.","Dados"],map:["Mapa","Visualize a geografia dos seus leads.","Geointeligência"]}[kind]||["HunterX","Workspace","HunterX"];
 if(kind==="leads")return <AppShell><PageHeader eyebrow={cfg[2]} title={cfg[0]} description={cfg[1]} action={<Link to="/app/leads/search" className="rounded-xl bg-white px-4 py-2 text-sm font-semibold text-black">+ Encontrar leads</Link>}/><div className="rounded-2xl border border-white/8 bg-white/[.035] divide-y divide-white/6">{leads.length?leads.map(x=><div key={x.id} className="flex items-center gap-4 p-5"><div className="flex-1"><b>{x.name}</b><div className="text-xs text-white/40 mt-1">{x.category||"Empresa"} · {x.city||"—"}</div></div><select value={x.status} onChange={async e=>{await updateLead(x.id,{status:e.target.value});setLeads(leads.map(y=>y.id===x.id?{...y,status:e.target.value}:y))}} className="rounded-lg border border-white/10 bg-black/20 p-2 text-xs"><option value="new">Novo</option><option value="contacted">Contatado</option><option value="qualified">Qualificado</option><option value="interested">Interessado</option><option value="negotiation">Negociação</option><option value="customer">Cliente</option><option value="lost">Sem interesse</option></select></div>):<div className="p-12 text-center text-white/40">Nenhum lead salvo ainda. Comece por uma pesquisa.</div>}</div></AppShell>;
 if(kind==="crm"){const stages=[["new","Novo"],["contacted","Contatado"],["qualified","Qualificado"],["interested","Interessado"],["negotiation","Negociação"],["customer","Clientes"],["lost","Sem interesse"]];return <AppShell><PageHeader eyebrow="Pipeline" title="CRM" description={cfg[1]}/><div className="grid gap-3 overflow-x-auto md:grid-cols-4 xl:grid-cols-7">{stages.map(([s,t])=><div key={s} className="min-h-64 rounded-2xl border border-white/8 bg-white/[.025] p-3"><div className="mb-3 flex justify-between text-sm font-semibold"><span>{t}</span><span className="text-white/30">{leads.filter(x=>x.status===s).length}</span></div>{leads.filter(x=>x.status===s).map(x=><div key={x.id} className="mb-2 rounded-xl border border-white/8 bg-white/[.04] p-3"><div className="text-sm">{x.name}</div><div className="mt-2 text-xs text-white/35">{x.city||"—"}</div><select value={x.status} onChange={async e=>{await updateLead(x.id,{status:e.target.value});setLeads(leads.map(y=>y.id===x.id?{...y,status:e.target.value}:y))}} className="mt-2 w-full rounded-lg bg-black/20 p-1.5 text-xs"><option value="new">Novo</option><option value="contacted">Contatado</option><option value="qualified">Qualificado</option><option value="interested">Interessado</option><option value="negotiation">Negociação</option><option value="customer">Cliente</option><option value="lost">Sem interesse</option></select></div>)}</div>)}</div></AppShell>}
 if(kind==="analytics"){const n=(s:string)=>leads.filter(x=>x.status===s).length;return <AppShell><PageHeader eyebrow="Inteligência" title="Analytics" description={cfg[1]}/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Leads",leads.length],["Contatados",n("contacted")],["Negociação",n("negotiation")],["Clientes",n("customer")]].map(x=><div className="rounded-2xl border border-white/8 bg-white/[.035] p-5" key={String(x[0])}><div className="text-xs text-white/40">{x[0]}</div><div className="mt-3 text-3xl font-semibold">{x[1]}</div></div>)}</div></AppShell>}
 if(kind==="lists"||kind==="campaigns"){const isList=kind==="lists";const add=async()=>{if(!name.trim())return;const r=isList?await createList(name):await createCampaign(name);setItems([...(Array.isArray(r)?r:[r]),...items]);setName("")};return <AppShell><PageHeader eyebrow={cfg[2]} title={cfg[0]} description={cfg[1]}/><div className="mb-5 flex gap-2"><input value={name} onChange={e=>setName(e.target.value)} placeholder={isList?"Nome da lista":"Nome da campanha"} className="h-11 flex-1 rounded-xl border border-white/10 bg-white/[.03] px-3 text-sm outline-none"/><button onClick={add} className="rounded-xl bg-white px-5 text-sm font-semibold text-black"><Plus size={15} className="mr-1 inline"/>Criar</button></div><div className="grid gap-4 md:grid-cols-3">{items.map(x=><div key={x.id} className="rounded-2xl border border-white/8 bg-white/[.035] p-5"><b>{x.name}</b><p className="mt-2 text-xs text-white/40">{x.description||"Sem descrição"}</p></div>)}</div></AppShell>}
 if(kind==="exports")return <AppShell><PageHeader eyebrow="Dados" title="Exportações" description={cfg[1]}/><div className="rounded-2xl border border-white/8 bg-white/[.035] p-6"><div className="font-semibold">{leads.length} leads disponíveis</div><button onClick={()=>{const cols=Object.keys(leads[0]||{name:""});const esc=(v:any)=>'"'+String(v??"").replaceAll('"','""')+'"';const csv="\\ufeff"+[cols.map(esc).join(","),...leads.map(r=>cols.map(c=>esc((r as any)[c])).join(","))].join("\\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="hunterx-leads.csv";a.click()}} disabled={!leads.length} className="mt-4 rounded-xl bg-white px-5 py-3 text-sm font-semibold text-black disabled:opacity-40"><Download size={15} className="mr-2 inline"/>Baixar CSV</button></div></AppShell>;
 return <AppShell><PageHeader eyebrow={cfg[2]} title={cfg[0]} description={cfg[1]}/><div className="grid min-h-[460px] place-items-center rounded-2xl border border-dashed border-white/10 bg-white/[.02]"><div className="text-center text-white/40"><MapPin size={30} className="mx-auto mb-3"/><div>Mapa preparado para integração.</div><p className="mt-2 text-xs">Os leads já armazenam latitude e longitude.</p></div></div></AppShell>;
}