const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});let charged=false;try{const auth=req.headers.get("Authorization")||"";if(!auth.startsWith("Bearer "))return json({error:"Faça login para pesquisar."},401);const gemini=Deno.env.get("GEMINI_API_KEY"),supabaseUrl=Deno.env.get("SUPABASE_URL"),anon=Deno.env.get("SUPABASE_ANON_KEY");if(!gemini||!supabaseUrl||!anon)return json({error:"Pesquisa web não configurada. Configure GEMINI_API_KEY no Supabase."},503);const userRes=await fetch(supabaseUrl+"/auth/v1/user",{headers:{apikey:anon,Authorization:auth}});if(!userRes.ok)return json({error:"Sessão inválida ou expirada."},401);const user=await userRes.json();if(!user?.id)return json({error:"Sessão inválida."},401);const body=await req.json(),query=String(body.query||"").trim(),location=String(body.location||"").trim();if(!query||!location)return json({error:"Informe o segmento e a localização."},400);
const qr=await fetch(supabaseUrl+"/rest/v1/rpc/consume_weekly_search",{method:"POST",headers:{apikey:anon,Authorization:auth,"Content-Type":"application/json"},body:"{}"});const qd=await qr.json(),quota=Array.isArray(qd)?qd[0]:qd;if(!qr.ok)return json({error:"Não foi possível verificar sua cota semanal."},500);if(!quota?.allowed)return json({error:"Você atingiu sua cota semanal de pesquisas web.",quota},429);charged=true;
const prompt="Encontre empresas reais para prospecção comercial. Pesquise na web usando Google Search. Segmento: "+query+". Localização: "+location+". Retorne SOMENTE JSON válido no formato {leads:[{name,website,phone,address,city,category,source_url,description}]}. Inclua somente empresas com evidência nos resultados pesquisados. Nunca invente dados. Priorize fontes oficiais. Deduplicate por nome+site. Máximo 20 empresas.";
const sr=await fetch("https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent",{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":gemini},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],tools:[{google_search:{}}],generationConfig:{responseMimeType:"application/json"}})});const sd=await sr.json();if(!sr.ok){await fetch(supabaseUrl+"/rest/v1/rpc/refund_weekly_search",{method:"POST",headers:{apikey:anon,Authorization:auth,"Content-Type":"application/json"},body:"{}"});return json({error:"A pesquisa do Google/Gemini não respondeu. Sua pesquisa foi devolvida."},502);}
const txt=sd.candidates?.[0]?.content?.parts?.[0]?.text;if(!txt){await fetch(supabaseUrl+"/rest/v1/rpc/refund_weekly_search",{method:"POST",headers:{apikey:anon,Authorization:auth,"Content-Type":"application/json"},body:"{}"});return json({error:"A IA não retornou resultados. Sua pesquisa foi devolvida."},502);}
let parsed:any;try{parsed=JSON.parse(txt)}catch{await fetch(supabaseUrl+"/rest/v1/rpc/refund_weekly_search",{method:"POST",headers:{apikey:anon,Authorization:auth,"Content-Type":"application/json"},body:"{}"});return json({error:"A resposta da pesquisa não pôde ser estruturada. Sua pesquisa foi devolvida."},502);}
const raw=Array.isArray(parsed?.leads)?parsed.leads:[],seen=new Set<string>(),leads=raw.filter((x:any)=>{const k=(String(x.name||"").toLowerCase().trim()+"|"+String(x.website||"").toLowerCase().trim());if(!x.name||seen.has(k))return false;seen.add(k);return true}).slice(0,20).map((x:any,i:number)=>({...x,id:"gemini-web-"+Date.now()+"-"+i,source:"gemini_google_search",query,location}));
await fetch(supabaseUrl+"/rest/v1/searches",{method:"POST",headers:{apikey:anon,Authorization:auth,"Content-Type":"application/json","Prefer":"return=minimal"},body:JSON.stringify({user_id:user.id,query,location,source:"gemini_google_search",filters:{},results_count:leads.length})}).catch(()=>{});
return json({leads,count:leads.length,quota,ai_enrichment:true,source:"Gemini + Google Search"});}catch(e){if(charged){try{const supabaseUrl=Deno.env.get("SUPABASE_URL"),anon=Deno.env.get("SUPABASE_ANON_KEY"),auth=req.headers.get("Authorization")||"";if(supabaseUrl&&anon)await fetch(supabaseUrl+"/rest/v1/rpc/refund_weekly_search",{method:"POST",headers:{apikey:anon,Authorization:auth,"Content-Type":"application/json"},body:"{}"})}catch{}}return json({error:e instanceof Error?e.message:"Falha na pesquisa web."},500)}});